# Generated by Django 5.1.2 on 2024-11-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_audiotourpoints_audiotoursubpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotourpoints',
            name='category',
            field=models.CharField(choices=[('art', 'Art'), ('history', 'History'), ('tourist', 'Tourist Attractions')], default='tourist', max_length=20),
        ),
    ]
