# Generated by Django 5.1.2 on 2024-11-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_audiotourpoints_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotourpoints',
            name='category',
            field=models.CharField(choices=[('art', 'Art'), ('history', 'History'), ('tourist', 'Tourist Attractions'), ('nature', 'Nature'), ('education', 'Education')], default='tourist', max_length=20),
        ),
    ]
