# Generated by Django 5.1.4 on 2024-12-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_friendrequest_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
